spring:
  datasource:
    url: jdbc:mysql://localhost/demo?autoReconnect=true&useSSL=false
    username: root
    password: wyy58023515
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
flyway:
  baselineOnMigrate: true